ALTER TYPE "Fase" ADD VALUE IF NOT EXISTS 'cetran';
ALTER TYPE "PromptTipo" ADD VALUE IF NOT EXISTS 'geracao_cetran';

ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "data_missing"   BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "valor_missing"  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "cnh_manual"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "analisado_em"   TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "dados_em"       TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "checkout_em"    TIMESTAMP(3);
